name: CI/CD pipline
on:
  push:
    branches: ["main"]

jobs:
  build-and-push-to-dh:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker thrift_comments service image
        run: |
          docker build . --tag ${{secrets.DOCKER_USERNAME }}/thrift_comments:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push thrift_comments service image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME}}/thrift_comments:latest
